### ISSUE TITLE
Wrong parameter order in log_message()

### ISSUE THREAD

**Issue by manuelbitmade** [factorial-io/phabalicious#100]
Hi,
I was using the new `log_message` command in a script and noticed that the documentation differs from the implementation. In https://factorial-io.github.io/phabalicious/scripts.html#internal-commands the order is message, severity but in https://github.com/factorial-io/phabalicious/blob/3.5.13/src/Scaffolder/Callbacks/LogMessageCallback.php#L35 it is reversed. 

I don't know what the preferred way would be so I don't attach a Patch for either the documentation or the implementation. I just wanted to let you know 😉

**Comment by stmh** [comment]
thanks for the heads up. Its an oversight in the documentation. the correct order is severity, message, where severity is optional.
