### ISSUE TITLE
"Could not get shell, as podForCli is empty!" regression

### ISSUE THREAD

**Issue by mikran** [factorial-io/phabalicious#130]
Running "phab -ckuberneteshost ssh" started giving "Could not get shell, as podForCli is empty!" after upgrade to 3.5.35

I downgraded phab to 3.5.34, same error

then down to 3.5.33, and now it started working again

so something in 3.5.33 -> 3.5.34 broke this

**Comment by stmh** [comment]
have you tried 3.5.35?

**Comment by stmh** [comment]
thanks for the report, will have a look.

**Comment by stmh** [comment]
should be fixed in 3.5.36
