### ISSUE TITLE
Add destination parameter to the put:file command

### ISSUE THREAD

**Issue by mikran** [factorial-io/phabalicious#137]
[Documentation](https://docs.phab.io/available-tasks.html#put-file) says that put:file command puts file to the `tmpFolder` but it looks like at least with k8s host the `rootFolder` is used as desination instead.

However when transferring big files it would be practical to get to choose where this file is transferred to as rootFolder or tmpFolder might not have enough space.

**Comment by stmh** [comment]
can be tested with 3.6.0-beta.7
