### ISSUE TITLE
Scaffolding an app which uses inheritsFrom with @ fails

### ISSUE THREAD

**Issue by mgrsskls** [factorial-io/phabalicious#150]
When scaffolding an app, which has this:
```
inheritsFrom:
  - "@/scaffold/drupal-fe/common.yml"
```
 I get the following error:
 ```
 …

 [ERROR] Could not get needed data from
         `https://config.factorial.io/scaffold/drupal-fe/%40/scaffold/drupal-fe/common.yml`!

In Scaffolder.php line 152:

  Missing key scaffold in scaffold: The file needs a scaffold-section.
  Missing key assets in scaffold: The file needs a assets-section.
  Missing key questions in scaffold: The file needs a questions-section.
 ```

**Comment by stmh** [comment]
sounds like the base url is missing

**Comment by stmh** [comment]
if you do not provide a base-url via the cli then the file must have sth like this:

```
baseUrl: https://config.factorial.io
```

**Comment by mgrsskls** [comment]
> sounds like the base url is missing

I ran it with `phab app:scaffold https://config.factorial.io/scaffold/drupal-fe/d9.yml --base-url https://config.factorial.io`, the scaffold file itself also has `baseUrl`

**Comment by stmh** [comment]
thanks for clarification. That sounds indeed like a bug. Will look into

**Comment by stmh** [comment]
fixed in https://github.com/factorial-io/phabalicious/releases/tag/3.6.4
