### ISSUE TITLE
Packagist cannot be reached reliably via IPv6

### ISSUE THREAD

**Issue by dride-for-sure** [factorial-io/phabalicious#164]
**Problem:**
If you use IPv6 and force connections to use IPv6 for outgoing connections first, I could not update `phab self-update`, cause `file_get_contents` will use the IPv6 address from packagist first, couldn't reach the `phabalicious.json`, although the domain is pingable via ipv6 (why packagist?, why? 🤯) and so runs into a connection timeout.

**Feature Request:**
It would be nice if `phab` falls back to IPv4, if IPv6 is not reachable, and tries again.

🙏🏽

**Comment by stmh** [comment]
if this is a showstopper for you try add `--offline` to your commands as a workaround unit a fix is ready -- this will prevent the update-check
