### ISSUE TITLE
Make "-cmbb" default when no config name is supplied

### ISSUE THREAD

**Issue by krisimmig** [factorial-io/phabalicious#167]
I mostly use phabalicious with the mbb config and I suggest we make that the default config name so we can just run `phab docker run` or `phab ssh` without the need to enter the mbb config name. Thoughts?

**Comment by stmh** [comment]
just set the `PHABALICIOUS_DEFAULT_CONFIG` to the config you want to use as default. (e.g. in you fish/zsh config)

Note that `mbb` is an implementation detail of our local setup and not enforced by phabalicious at all.

I'll keep the ticket open, as this environment variable is not documented as far as I remember

**Comment by krisimmig** [comment]
Ok, I didn't know about that one, will do! 👍

**Comment by stmh** [comment]
documented in 3.7 betas
