### ISSUE TITLE
[feature-request]  It would be cool if you can generate htaccess passwords.

### ISSUE THREAD

**Issue by mbutkereit** [factorial-io/phabalicious#186]
For scaffolding it would be helpful if you could convert the values to a htaccess password.

Example basic auth at ingress.

**Comment by stmh** [comment]
Are htpasswd hashed via md5? Then you can test the 3.7 beta (no release yet, you need to check out the repo and run it manually)

**Comment by stmh** [comment]
Implemented with 3.7.0
