### ISSUE TITLE
'error: unexpected EOF' when doing 'get:files-dump'

### ISSUE THREAD

**Issue by joachim-n** [factorial-io/phabalicious#190]
I did:

```
phab -cmain-live get:files-dump
```

This was the output:

```
tar: Removing leading `/' from member names
error: unexpected EOF


 [ERROR] [3092cb] error: unexpected EOF



tar: Removing leading `/' from member names

Copied dumps to:
================

 * main-live.private.20210901120948.tgz
 ```

I actually got two files created:

```
-rw-r--r--   1 joachim  staff       39983  1 Sep 12:39 main-live.private.20210901120948.tgz
-rw-r--r--   1 joachim  staff  7625661952  1 Sep 12:38 main-live.public.20210901110905.tgz
```

**Comment by joachim-n** [comment]
It turns out that the `main-live.public.20210901110905.tgz` file is broken.

**Comment by stmh** [comment]
check your `kubectl` version. This seems like a bug in  newer versions. Try downgrading to kubectl 1.19. 

https://github.com/kubernetes/kubernetes/issues/60140

**Comment by mikran** [comment]
This is exactly the error I've had in pipelines but what I've been unable to reproduce locally.

But that version thing does not add up, my local kubectl is 1.22 and gitlab-runner has 1.19

**Comment by stmh** [comment]
there's a new feature flag in the 3.8 branch for using  `rsync` internally instead of `kubectl cp`. As rsync needs to be available in the target pod this is an optional feature which can be enabled by 

```
host:
  name:
    kube:
      useRsync: true
```
