### ISSUE TITLE
drush php doesn't work within phab shell, but works directly

### ISSUE THREAD

**Issue by joachim-n** [factorial-io/phabalicious#194]
I did:

```
phab -cmain-live shell
drush php
$ids = \Drupal::entityQuery('crop')->execute(); dump($ids);
```

and I got:

> Drupal\Core\Database\DatabaseExceptionWrapper with message 'SQLSTATE[HY000]: General error: 2006 MySQL server has gone away: INSERT INTO {cache_discover [ETC]

However when I did this:

```
phab -cmain-live drush -- php
$ids = \Drupal::entityQuery('crop')->execute(); dump($ids);
```

it ran perfectly.

**Comment by stmh** [comment]
I cant reproduce this on my end. As the only difference between both code-paths is that the former gives you an interactive shell while the latter just an ordinary shell, I wonder if this was a temporary Drupal related problem.

It seems that the mysql configuration needs to be adjusted on that host, e.g. increase `max_allowed_packet` to prevent  dying mysql processes.

**Comment by joachim-n** [comment]
Ok, just worked for me now too!
