### ISSUE TITLE
[feature-request] Allow sql-drop with restore:sql-from-file

### ISSUE THREAD

**Issue by mikran** [factorial-io/phabalicious#197]
command copy:from is hard-coded to always do sql-drop
command restore:sql-from-file is hard-coded to never do sql-drop

I'd like these commands to be consistent and do the same thing(sql-drop) by default, and then maybe a parameter `--skip-sql-drop` to not do it.

**Comment by stmh** [comment]
I used a slightly different naming but it is implemented here: https://github.com/factorial-io/phabalicious/releases/tag/3.7.0-beta.9
