### ISSUE TITLE
Do not call task copyFromPrepareSource on method mysql with `phab copy-from <xxx> files`

### ISSUE THREAD

**Issue by mikran** [factorial-io/phabalicious#212]
`phab copy-from <xxx> files` command failed with "Could not connect to database!".

Database should not be needed when copying just the files.

**Comment by stmh** [comment]
can you try latest `main`? should contain a fix for this scenario.

**Comment by stmh** [comment]
please try 3.7.4

**Comment by mikran** [comment]
I had to do it with get:file & put:file, it did not work with docker-exec nor kubectl

**Comment by stmh** [comment]
copy-from is using rsync internally and this is not supported for specific combinations of shell-providers, as we need to pass a "connection-string" to rsync so it can reach the source originating from the target-shell. (or the other way around). There is some preliminary work in the 3.8-branch where I am replacing `kubectl cp` with rsync which might be also a way to make it working for certain, currently unsupported combinations.

**Comment by stmh** [comment]
this should be fixes in latest 3.7.x. Please reopen if still the case.
