### ISSUE TITLE
DB related tasks fail

### ISSUE THREAD

**Issue by manuelbitmade** [factorial-io/phabalicious#215]
Hi,
I'm currently stuck using Phabalicious `3.6.16` because starting with `3.7` I keep getting this error:

```
PHP Notice:  Trying to access array offset on value of type null in phar:///usr/local/bin/phab/src/Method/DrushMethod.php on line 692

Notice: Trying to access array offset on value of type null in phar:///usr/local/bin/phab/src/Method/DrushMethod.php on line 692
PHP Notice:  Undefined index:  in phar:///usr/local/bin/phab/src/Method/DrushMethod.php on line 692

Notice: Undefined index:  in phar:///usr/local/bin/phab/src/Method/DrushMethod.php on line 692
PHP Warning:  Invalid argument supplied for foreach() in phar:///usr/local/bin/phab/src/Method/DrushMethod.php on line 692

Warning: Invalid argument supplied for foreach() in phar:///usr/local/bin/phab/src/Method/DrushMethod.php on line 692
PHP Notice:  Trying to access array offset on value of type null in phar:///usr/local/bin/phab/src/Method/DrushMethod.php on line 695

Notice: Trying to access array offset on value of type null in phar:///usr/local/bin/phab/src/Method/DrushMethod.php on line 695

In DatabaseMethod.php line 323:

  Missing key host in database: the database-host
  Missing key user in database: the database user
  Missing key pass in database: the password for the database-user
  Missing key name in database: the database name to use
```

I looked into the source code and it seems that for whatever reason the Drush method is not able to get the database credentials from config/settings.php. However executing `drush sql:conf --show-passwords --format=json` on the server does output something I'd expect:

![Bildschirmfoto 2021-12-14 um 16 03 58](https://user-images.githubusercontent.com/1777091/146024183-c7b87147-e9da-4f98-91e1-0e96b2ba17c1.jpg)

We are using Drupal 9 with Drush 10.5.0. Let me know if you have any idea or if you need more information. Thanks for the great tool 🙏

**Comment by stmh** [comment]
Hi Please try the version of this branch on your project:

https://github.com/factorial-io/phabalicious/tree/bugfix/missing-db-credentials-215

(clone, run composer install, then run `path/to/phabalicious/bin/phab your-command` to see if you get an error report or even better if it works now on your config.

the old version does not honour exotic install paths of drush.

**Comment by manuelbitmade** [comment]
Hi @stmh 
I now get an SQL error which didn't appear before. 

```
mysqldump: Got error: 1044: "Access denied for user 'xxx'@'localhost' to database 'xxx'" when using LOCK TABLES
```

This is the command Phab is trying to execute.
```shell
mysqldump -u XXX -h localhost --port 3306 -p'xxx-xxx' XXX --add-drop-table --no-autocommit --no-data > /tmp/stage.20211215101215
```

I have to say that in the past we had some weird databse permission issues in this project so it might be related. However it does work with an older version of Phab.

**Comment by stmh** [comment]
hi @manuelbitmade 
can you pull and try again? I added the same dump options as drush now.

**Comment by stmh** [comment]
Please try version 3.7.5

**Comment by manuelbitmade** [comment]
Hi @stmh 
sorry I didn't respond, I'll try the new version as soon as possible and let you know if this is fixed.

Thanks for your work!

**Comment by manuelbitmade** [comment]
I just tested the new version and the task that failed is now executed successfully 🎉 

I'm closing the issue, seems to be solved 👍
