### ISSUE TITLE
[feature request] Allow dump file for install:from

### ISSUE THREAD

**Issue by mikran** [factorial-io/phabalicious#223]
As a new member to project I might not have access to all the environments yet, and database dump file is easier to get access to than the access required to run `install:from host-config`

But using this method (file) to get the database is rather complex at the moment

Normally I'd do that with `restore:sql-from-file`, but that fails as database does not exist

To create database I would run `drush sql:create`, but that fails because drush does not exist (composer install)

So these two steps above are performed by `install:from` but not with `restore:sql-from-file`

This can be done by running `install` first followed by `restore:sql-from-file`, but install can be really slow.

**Feature request:**

Add a command that merges the functionality of  `install:from host-config` and `restore:sql-from-file`

**Comment by stmh** [comment]
there's a feature branch (which is based on a lot of changed stuff which needs further testing) but maybe you want to give it a try: https://github.com/factorial-io/phabalicious/tree/feature/install-from-sql-file

**Comment by stmh** [comment]
Released with 3.8.0
