### ISSUE TITLE
Allow all project configuration files to be in one directory

### ISSUE THREAD

**Issue by joachim-n** [factorial-io/phabalicious#249]
It would help with discoverability and learnability if all of the project's config files were in one place.

e.g. at the moment I need to increase PHP's memory limit. I have no idea how to do this.

My strategy at a point like this is to look in the config files for an existing setting I can change. But these are scattered all over, and I am never sure if I have found them all:

- .phab/k8s.yml
- .fabfile.yaml
- docker-compose-FOO.yml

If all of these files were instead in a subfolder, I could search them all at once and know I'd covered all over them.

**Comment by stmh** [comment]
that's hard to implement, as every project uses different tools and setups. phab does not "own" the docker-compose.yml and some of the config files needs to be stored  in specific places so the used tooling find them. There's already existing work in 3.7.x to scaffold the project configuration when needed into a single file, but this needs to be adapted for every project. 

Even if these files are in the same folder, it wouldn't help you to change the memory limit, as that is configured somewhere else (e.g. in the php.ini file of your docker container, or in a settings.php or .htaccess file)

**Comment by joachim-n** [comment]
I don't understand -- on the Jira for the WSD project you said this was something to deal with in Phab, rather than per-project, and here you seem to be saying it's up to each project.

I just want to be able to shell into the project so I can run Drush commands, as doing `phab drush` is tediously slow. Having to `cd` each time is also tedious.

**Comment by stmh** [comment]
I think your last comment is referring issue #253 -- having all project files in a dedicated folder (this issue) and where you end up when running `phab shell` (#253) are not related.

**Comment by joachim-n** [comment]
Argh, sorry!

**Comment by stmh** [comment]
as phab is kind of an "umbrella" tool and needs to be flexible to adapt to different project setup I do not see a way to enforce this.
