### ISSUE TITLE
Updating phabalicious causes error

### ISSUE THREAD

**Issue by krisimmig** [factorial-io/phabalicious#25]
When using the buildin update function the update is successfull but I get am error message at the end:

> 17:49:05 > phab self-update --allow-unstable=1
> 
> 
>  Version 3.0.0-beta.3 of phabalicious is available. Run `phab self-update --allow-unstable=1` to update your local
>  installation.
> 
>  Visit https://github.com/factorial-io/phabalicious/releases for more info.
> 
> 
> 
>  Current version is 3.0.0-beta.2, looking for a new version ...
> 
> 
>  [OK] Updated phabalicious successfully to 3.0.0-beta.3
> 
> 
> PHP Warning:  Uncaught ErrorException: Warning: require(phar:///usr/local/bin/phab/vendor/composer/../symfony/console/Event/ConsoleTerminateEvent.php): failed to open stream: phar error: internal corruption of phar "/usr/local/bin/phab" (actual filesize mismatch on file "vendor/symfony/console/Event/ConsoleTerminateEvent.php") in phar:///usr/local/bin/phab/vendor/symfony/debug/DebugClassLoader.php:151
> Stack trace:
> #0 phar:///usr/local/bin/phab/vendor/symfony/console/Application.php(933): spl_autoload_call('Symfony\\Compone...')
> #1 phar:///usr/local/bin/phab/vendor/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(Phabalicious\Command\SelfUpdateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #2 phar:///usr/local/bin/phab/vendor/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutp in phar:///usr/local/bin/phab/vendor/symfony/debug/DebugClassLoader.php on line 151
> PHP Fatal error:  Symfony\Component\Debug\DebugClassLoader::loadClass(): Failed opening required 'phar:///usr/local/bin/phab/vendor/composer/../symfony/console/Event/ConsoleTerminateEvent.php' (include_path='.:') in phar:///usr/local/bin/phab/vendor/symfony/debug/DebugClassLoader.php on line 151
> PHP Fatal error:  require(): Failed opening required 'phar:///usr/local/bin/phab/vendor/composer/../symfony/debug/Exception/FatalErrorException.php' (include_path='.:') in phar:///usr/local/bin/phab/vendor/symfony/debug/DebugClassLoader.php on line 151

**Comment by stmh** [comment]
Closing in favor of #24
