### ISSUE TITLE
Make `phab shell` go to the working dir of the app

### ISSUE THREAD

**Issue by joachim-n** [factorial-io/phabalicious#253]
Some projects using phab are set up in such a way that `phab shell` starts you in the working dir of the app, which is the root of the Composer project. This is useful because you can immediately run Drush commands, for instance.

On other projects, `phab shell` takes you to the root user's folder, which means every time you do it you have to remember to `cd /var/www`.

**Comment by mikran** [comment]
That `rootFolder` can be configured in host settings, see https://docs.phab.io/docker-integration.html#a-docker-configuration
