### ISSUE TITLE
self-update --allow-unstable=1 toggles between stable and unstable version

### ISSUE THREAD

**Issue by d34dman** [factorial-io/phabalicious#260]
## How to reproduce the issue?

Execute `sudo phab self-update --allow-unstable=1` again and again.

## Expected behaviour
phab updates itself to latest unstable version.

## Current behaviour

phab updates toggles between latest stable and unstable version.

![phab-unstable-update](https://user-images.githubusercontent.com/1006481/158131696-4f723b60-deac-4a40-9a3d-e7c9814836a4.png)

## System Info

- PHP 7.4.3
- Operating System: Ubuntu 20.04.3 LTS
- Kernel: Linux 5.4.0-96-generic
- Architecture: x86-64

## Workaround 

Execute `sudo phab self-update --allow-unstable=1` until you get the desired version.

**Comment by stmh** [comment]
or just skip `--allow-unstable` as this prefers beta-versions. But nevertheless if the latest stable precedes a beta it should choose the stable instead of the older beta. 

Please test `3.8-beta` as it uses a different approach for `self-update`
