### ISSUE TITLE
notify channel option does not accept a value

### ISSUE THREAD

**Issue by mikran** [factorial-io/phabalicious#261]
I was looking for a way to direct some notifications to a different channel, and command is not working the way it is documented.

[Docs](https://docs.phab.io/commands.html#notify) says that syntax is:

`phab -cmbb notify "test" "kubernetes"`

but that gives

`Too many arguments, expected arguments "command" "message".`

`phab notify --help`

describes syntax as

```
Description:
  Will send a notification

Usage:
  notify [options] [--] <message>

Arguments:
  message                          The message to send

Options:
  ...
  -4, --channel
  ...
```

and running it like that gives

`phab -cmbb notify --channel="kubernetes" -- "test"`

`The "--channel" option does not accept a value.`

**Comment by stmh** [comment]
part of 3.7.8
