### ISSUE TITLE
docs: unwanted line breaks

### ISSUE THREAD

**Issue by stmh** [factorial-io/phabalicious#287]
the markdown implementation treats linefeeds differently to the standard:

```
Phab 3.8 contains a new command named `find:property` which provides a visual prompt where the user can start typing the
name of a property they are interested in. Phab supports you by offering properties via autocomplete. As an alternative
you can hit enter to get a list of suggestions. After you found the property you are interested in, hit return, and phab
will display the actual value of that property, its ancestors and from where it got read.
```

gets rendered with line breaks after every source-line: 
<img width="822" alt="CleanShot 2022-09-24 at 16 06 29@2x" src="https://user-images.githubusercontent.com/319208/192102610-20615190-3c57-49a5-ace4-f0d67e061b37.png">

According to the markdown spec this shouldn't happen, if you want to add a line break, you need to add 2 spaces. (See also: https://gist.github.com/shaunlebron/746476e6e7a4d698b373)

Is this configurable per project? if so how?

**Comment by mgrsskls** [comment]
Ah, thanks for the hint! That was a simple internal setting which is not configurable though. PR: https://github.com/factorial-io/phabalicious/pull/288

**Comment by stmh** [comment]
thanks!
