### ISSUE TITLE
putfile --destination option docs don't explain what it is

### ISSUE THREAD

**Issue by joachim-n** [factorial-io/phabalicious#300]
>   -d, --destination[=DESTINATION]  The target destination to copy the file to

Is this a full path that gets written? A directory, which means the source filename is preserved, or can I give a filepath with the filename too? What if I give just a filename, where does it go?

Or is it something totally different, like a server?

**Comment by stmh** [comment]
you can provide a relative or absolute path including filename via `--destination`. Tried to clarify the docs and help.
