### ISSUE TITLE
phabalicious quits with an error when interaction is required while running composer

### ISSUE THREAD

**Issue by d34dman** [factorial-io/phabalicious#42]
When some interaction is required while running composer, phabalicious quits by giving error like the following.
```
[Phabalicious\Exception\FailedShellCommandException]           
  `cd /var/www && composer install` failed!                      
  Gathering patches for root package.                            
  Gathering patches for root package.                            
  Gathering patches for dependencies. This might take a minute.
```
The above error was resolved by running `composer install` directly in console and then carrying on with `phab -cmbb reset`

**Comment by stmh** [comment]
this won't be fixed in the near future. When running commands in a script there's no terminal available. Instead update your composer.json with 
```json
 "config": {
      "discard-changes": true,
      ....
}
```
