### ISSUE TITLE
install task fails for Drupal 8 without any configuration 

### ISSUE THREAD

**Issue by stmh** [factorial-io/phabalicious#45]
to reproduce:

1. Scaffold a new d8-project
2. run `phab -cmbb install` on that project
3. after a while, you'll get an error message that drupal can't import an empty folder

This error should also show up on the reset-task without any configuration

**Comment by mikran** [comment]
From my experience install task often fails for Drupal 8 with configuration too. This would be a good place to add support for `drush site-install --existing-config` command option and then config-import command can be removed from install task and that solves both cases... for some distributions.

It would deprecate `uuid` configuration and `installOptions` would only apply for first installs.

**Comment by stmh** [comment]
Fixed in 3.5.x
