### ISSUE TITLE
Fix invalid `.fabfile.yaml` for FR012 project

### ISSUE THREAD

**Issue by d34dman** [factorial-io/phabalicious#5]
when trying to run drush status on config mbb, it is throwing error in fr012. 

    phab drush -c mbb status                                                                                                                           
    Could not validate config `mbb`
    Missing key rootFolder in dockerHost: `default`: The rootFolder to start with

**Comment by stmh** [comment]
Remove the section or add `inheritOnly` The new architecture validates all docker configs, and default is invalid.

I'd remove the section, as it is a copy-paste relict from over two years ago.
