### ISSUE TITLE
Allow environment variables for hosts

### ISSUE THREAD

**Issue by stmh** [factorial-io/phabalicious#56]
Currently only `dockerHosts` can have environment variables. It would be neat to extend that feature to hosts

**Comment by d34dman** [comment]
@stmh  this will be of great value. This will allow us to use custom scripts with Acquia Dev Desktop setup. Right now using drush command inside custom script doesn't work.

**Comment by stmh** [comment]
check your custom scripts that drush is used via `#!drush`, then custom scripts will work with the current solution

**Comment by stmh** [comment]
as learned from a different project, environment variables set on the container are not available when running drush, so this gets a higher priority
