### ISSUE TITLE
Artifcat deployment fails if commit message has double quotes.

### ISSUE THREAD

**Issue by d34dman** [factorial-io/phabalicious#62]
During the final stage of deployment, a commit message is created by concatenating previous messages. If one of these previous message has double quoted string, this leads to wrong command being generated and executed.

Eg.

Let say we have a following commit message, `Revert "Disable deployment to develop"`.
This would try to create a command,

```
[notice] cd /tmp/artifact-xxx-target-1574011188 && git commit -m "xxxxxxxx Revert "Disable deployment to mi009"" || true
```

Which results in following error,

```
error: pathspec 'deployment' did not match any file(s) known to git
error: pathspec 'to' did not match any file(s) known to git
error: pathspec 'mi009' did not match any file(s) known to git
```

Proposed solution,

- Escape the commit messages with backslash, while synthesising the terminal command.

**Comment by stmh** [comment]
merged back to develop. develop needs some more love before doing a release.

**Comment by stmh** [comment]
Fix is in master.
