### ISSUE TITLE
Better support for helper classes in Transformers

### ISSUE THREAD

**Issue by d34dman** [factorial-io/phabalicious#72]
> The mighty Transformers could use some help and support :)

So I decided to use an abstract base class to extend the a custom transformer I was writing.

I created a transformer [BlockContentTypeTransformer](https://github.com/factorial-io/phab-entity-scaffolder/blob/feature/block_content.type/src/transformers/BlockContentTypeTransformer.php) .

When i try to extend with a base class as such, it borks during usage,
[BlockContentTypeTransformer](https://github.com/factorial-io/phab-entity-scaffolder/blob/feature/block_content.type/src/transformers/BlockContentTypeTransformer.php) extends [EntityTransformerBase](https://github.com/factorial-io/phab-entity-scaffolder/blob/feature/block_content.type/src/transformers/EntityTransformerBase.php)

Unfortunately, EntityTransformerBase **doesn't get autoloaded** it seems when trying to execute `phab scaffold <path-to-your-scaffold.yml>`

**Comment by stmh** [comment]
As a quick fix add a `require_oncd __DIR__ . '/yourclass.php'` -- Getting autoload working will be tricky, as we cant just consume `autoload.php` of the project.

**Comment by d34dman** [comment]
Thanks for the latest fixes :) This is no longer an issue.
