### ISSUE TITLE
Get latest created backup

### ISSUE THREAD

**Issue by timlie** [factorial-io/phabalicious#84]
Hi,

First of all, thanks for this great piece of code! I started working with this package for some everyday tasks with Drupal.

I also tried the backup files and it works really well.
My question is if we can automate the creation of the backup and downloading it to my computer at once?

Now we need to backup, get hash and then give the command for downloading it.
Can we download the last created backup right after the creation? 

Thanks!

**Comment by stmh** [comment]
Hi @timlie 

This is currenty not supported (yet). What's your usecase? Can you add some context?

If you just want the current remote db you can use `phab -c<config> get:sql-dump` or `phab -c<config> get:files-dump> for files. This will copy the files to your local, without storing them on the remote.

If you want to copy data from one installation to another you can use the copy-from command, e.g. `phab -c<target> copy-from <source>`

HTH,
Stephan

**Comment by timlievens** [comment]
Hi Stephan,

Thanks for your reply.
Probably the use case is out of scope for this package. I was checking if I could automate an offsite backup for the files from a Drupal site.
I will check on get:files-dump as this may be a solution as well.

Greetings,
Tim

**Comment by timlie** [comment]
Hi Stephan,

Thanks for your reply.
Probably the use case is out of scope for this package. I was checking if I could automate an offsite backup for the files from a Drupal site.
I will check on get:files-dump as this may be a solution as well.

Greetings,
Tim
