### ISSUE TITLE
uuid error on d7 site

### ISSUE THREAD

**Issue by Opswatch** [factorial-io/phabalicious#99]
For a D7 site do we need to specify in the fab config file that its d7?, when trying to run phab against a d7 site I get a Drupal 8 needs a global uuid-setting, but its a d7 site.

**Comment by stmh** [comment]
Hi,

Set `drupalVersion` to `7` (on the global scope or per host). see https://factorial-io.github.io/phabalicious/configuration.html#configuration-for-the-drush-method for more info

**Comment by Opswatch** [comment]
Awesome, thanks for the great tool.
